<?xml version="1.0" encoding="utf-8"?><Database Name="PetShop" Class="DataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=PetShop;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="IntegrativeMidterm.Properties.Settings" SettingsPropertyName="PetShopConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.spAddGeneralStatus" Method="spAddGeneralStatus">
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spAddMedicalType" Method="spAddMedicalType">
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Price" Parameter="price" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spAddPetBreed" Method="spAddPetBreed">
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spGetPetStatus" Method="spGetPetStatus">
    <ElementType Name="spGetPetStatusResult">
      <Column Name="pet_status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spAddPetStatus" Method="spAddPetStatus">
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spAddPetSupply" Method="spAddPetSupply">
    <Parameter Name="pet_supply_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pet_supply_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="image_path" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spAddPetType" Method="spAddPetType">
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spAddSupplyType" Method="spAddSupplyType">
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spAddTransactionType" Method="spAddTransactionType">
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spCreateMedicalHistory" Method="spCreateMedicalHistory">
    <Parameter Name="pet_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="medical_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="description" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="process_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="staff_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="image_path" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spGetAllMedicalHistories" Method="spGetAllMedicalHistories">
    <Parameter Name="medical_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="from_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="to_date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="spGetAllMedicalHistoriesResult">
      <Column Name="[Record ID]" Member="Record_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Pet ID]" Member="Pet_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Pet Name]" Member="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Medical Type]" Member="Medical_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Process date]" Member="Process_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Staff" Type="System.String" DbType="VarChar(102) NOT NULL" CanBeNull="false" />
      <Column Name="[Image path]" Member="Image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Medical Type ID]" Member="Medical_Type_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Pet ID1]" Member="Pet_ID1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Record ID1]" Member="Record_ID1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Staff ID]" Member="Staff_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetAllPetSupplyTransactions" Method="spGetAllPetSupplyTransactions">
    <Parameter Name="from_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="to_date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="spGetAllPetSupplyTransactionsResult">
      <Column Name="[Transaction ID]" Member="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Total Cost]" Member="Total_Cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Quantity Sold]" Member="Quantity_Sold" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Process Date]" Member="Process_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Staff" Type="System.String" DbType="VarChar(102) NOT NULL" CanBeNull="false" />
      <Column Name="[Staff ID]" Member="Staff_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetAllPetTransactions" Method="spGetAllPetTransactions">
    <Parameter Name="from_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="to_date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="spGetAllPetTransactionsResult">
      <Column Name="[Transaction ID]" Member="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Pet name]" Member="Pet_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Customer name]" Member="Customer_name" Type="System.String" DbType="VarChar(102) NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Process Date]" Member="Process_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Staff" Type="System.String" DbType="VarChar(102) NOT NULL" CanBeNull="false" />
      <Column Name="[Pet image path]" Member="Pet_image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Customer image path]" Member="Customer_image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Staff ID]" Member="Staff_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Pet ID]" Member="Pet_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Customer ID]" Member="Customer_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetAllTransactions" Method="spGetAllTransactions">
    <Parameter Name="from_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="to_date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="spGetAllTransactionsResult">
      <Column Name="[Transaction ID]" Member="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Total Cost]" Member="Total_Cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Quantity Sold]" Member="Quantity_Sold" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Process Date]" Member="Process_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Transaction Type]" Member="Transaction_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff" Type="System.String" DbType="VarChar(102) NOT NULL" CanBeNull="false" />
      <Column Name="[Staff ID]" Member="Staff_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Transaction Type ID]" Member="Transaction_Type_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetCustomerData" Method="spGetCustomerData">
    <Parameter Name="customer_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetCustomerDataResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Middle Name]" Member="Middle_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Contact Number]" Member="Contact_Number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Email Address]" Member="Email_Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Home Address]" Member="Home_Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Image path]" Member="Image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetMedicalHistory" Method="spGetMedicalHistory">
    <Parameter Name="medical_history_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetMedicalHistoryResult">
      <Column Name="[Record ID]" Member="Record_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Pet ID]" Member="Pet_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Pet Name]" Member="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Medical Type]" Member="Medical_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Process date]" Member="Process_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Staff" Type="System.String" DbType="VarChar(102) NOT NULL" CanBeNull="false" />
      <Column Name="[Image path]" Member="Image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Staff ID]" Member="Staff_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Medical Type ID]" Member="Medical_Type_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetMedicalTypes" Method="spGetMedicalTypes">
    <ElementType Name="spGetMedicalTypesResult">
      <Column Name="medical_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetPetData" Method="spGetPetData">
    <Parameter Name="pet_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetPetDataResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Species" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Breed" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Image path]" Member="Image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Species ID]" Member="Species_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Breed ID]" Member="Breed_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Status ID]" Member="Status_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetPetMedicalHistory" Method="spGetPetMedicalHistory">
    <Parameter Name="pet_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetPetMedicalHistoryResult">
      <Column Name="[Record ID]" Member="Record_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Pet ID]" Member="Pet_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Pet Name]" Member="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Medical Type]" Member="Medical_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Process date]" Member="Process_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Staff" Type="System.String" DbType="VarChar(102) NOT NULL" CanBeNull="false" />
      <Column Name="[Image path]" Member="Image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Staff ID]" Member="Staff_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Medical Type ID]" Member="Medical_Type_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetPetSupply" Method="spGetPetSupply">
    <Parameter Name="pet_supply_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetPetSupplyResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Product name]" Member="Product_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Supply Type]" Member="Supply_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Species" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Image path]" Member="Image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Status ID]" Member="Status_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Supply Type ID]" Member="Supply_Type_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Species ID]" Member="Species_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetPetSupplyTypes" Method="spGetPetSupplyTypes">
    <ElementType Name="spGetPetSupplyTypesResult">
      <Column Name="pet_supply_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetPetTransactionHistory" Method="spGetPetTransactionHistory">
    <Parameter Name="transaction_history_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetPetTransactionHistoryResult">
      <Column Name="[Transaction ID]" Member="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Pet name]" Member="Pet_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Customer name]" Member="Customer_name" Type="System.String" DbType="VarChar(102) NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Process Date]" Member="Process_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Staff" Type="System.String" DbType="VarChar(102) NOT NULL" CanBeNull="false" />
      <Column Name="[Pet image path]" Member="Pet_image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Customer image path]" Member="Customer_image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Staff ID]" Member="Staff_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Pet ID]" Member="Pet_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Customer ID]" Member="Customer_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetPetTypes" Method="spGetPetTypes">
    <ElementType Name="spGetPetTypesResult">
      <Column Name="pet_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetStaffData" Method="spGetStaffData">
    <Parameter Name="staff_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetStaffDataResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Middle Name]" Member="Middle_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Contact Number]" Member="Contact_Number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Email Address]" Member="Email_Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Home Address]" Member="Home_Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Image path]" Member="Image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetSupplyTransactionHistory" Method="spGetSupplyTransactionHistory">
    <Parameter Name="transaction_history_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetSupplyTransactionHistoryResult">
      <Column Name="[Transaction ID]" Member="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Total Cost]" Member="Total_Cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Quantity Sold]" Member="Quantity_Sold" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Process Date]" Member="Process_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Staff" Type="System.String" DbType="VarChar(102) NOT NULL" CanBeNull="false" />
      <Column Name="[Staff ID]" Member="Staff_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetTransactionTypes" Method="spGetTransactionTypes">
    <ElementType Name="spGetTransactionTypesResult">
      <Column Name="transaction_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spRegisterCustomer" Method="spRegisterCustomer">
    <Parameter Name="first_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="middle_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="last_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="gender" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="birthdate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="contact_number" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="email_address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="image_path" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spUpdateSupplyData" Method="spUpdateSupplyData">
    <Parameter Name="pet_supply_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_supply_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pet_supply_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="image_path" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spRegisterPet" Method="spRegisterPet">
    <Parameter Name="pet_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="gender" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="birthdate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pet_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_breed_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="image_path" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spRegisterStaff" Method="spRegisterStaff">
    <Parameter Name="first_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="middle_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="last_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="gender" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="birthdate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="contact_number" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="email_address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="image_path" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spSetPetStatus" Method="spSetPetStatus">
    <Parameter Name="pet_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_status_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spSetPetSupplyStatus" Method="spSetPetSupplyStatus">
    <Parameter Name="pet_supply_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="status_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spTransactionAddPet" Method="spTransactionAddPet">
    <Parameter Name="transaction_history_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spTransactionAddSupply" Method="spTransactionAddSupply">
    <Parameter Name="transaction_history_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="purchase_quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_supply_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spTransactionCreate" Method="spTransactionCreate">
    <Parameter Name="transaction_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="transaction_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="staff_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="customer_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spUpdateCustomerData" Method="spUpdateCustomerData">
    <Parameter Name="customer_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="first_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="middle_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="last_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="gender" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="birthdate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="contact_number" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="email_address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="image_path" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spUpdatePetData" Method="spUpdatePetData">
    <Parameter Name="pet_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="gender" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="birthdate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pet_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_breed_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="image_path" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spUpdateStaffData" Method="spUpdateStaffData">
    <Parameter Name="staff_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="first_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="middle_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="last_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="gender" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="birthdate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="contact_number" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="email_address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="image_path" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spGetSupplyTransactionSummary" Method="spGetSupplyTransactionSummary">
    <Parameter Name="transaction_history_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetSupplyTransactionSummaryResult">
      <Column Name="[Parent Transaction ID]" Member="Parent_Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Supply name]" Member="Supply_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Supply type]" Member="Supply_type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Species" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Price per item]" Member="Price_per_item" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Purchase Quantity]" Member="Purchase_Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Supply image path]" Member="Supply_image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Supply Type ID]" Member="Supply_Type_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Species ID]" Member="Species_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetAllPets" Method="spGetAllPets">
    <Parameter Name="pet_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_breed_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="gender" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pet_status_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetAllPetsResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Species" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Breed" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Image path]" Member="Image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Species ID]" Member="Species_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Breed ID]" Member="Breed_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Status ID]" Member="Status_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetAllPetSupplies" Method="spGetAllPetSupplies">
    <Parameter Name="pet_supply_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_type_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pet_supply_status_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetAllPetSuppliesResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Product name]" Member="Product_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Supply Type]" Member="Supply_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Species" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Image path]" Member="Image_path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Status ID]" Member="Status_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Supply Type ID]" Member="Supply_Type_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Species ID]" Member="Species_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetPetBreeds" Method="spGetPetBreeds">
    <Parameter Name="pet_type_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetPetBreedsResult">
      <Column Name="pet_breed_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pet_type_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>